name: ml
channels:
 - defaults
 - conda-forge
 - pytorch
 - nvidia
dependencies:
 - python=3.10
 - pytest=7.4.0
 - pip=23.3.1
 - numpy=1.26.3
 - pandas=2.1.4
 - bokeh=3.3.4
 - seaborn=0.12.2
 - matplotlib=3.8.2
 - opencv=4.9.0
 - scikit-image=0.22.0
 - jupyter=1.0.0
 - jupyter-book=0.15.1
 - pytorch=2.2.0
 - pytorch-cuda=12.1
 - torchvision=0.17.0
 - torchaudio=2.2.0
